name: donnabot-service
version: '0.0.13.6'
synopsis: donnabot.dev service
description: donnabot.dev Service
category: Web
author: Donna <donna@kott.is>
maintainer: Donna <donna@kott.is>
copyright: 2020 Donna
license: MIT
git: https://www.gitlab.com/naglalakk/donnabot-service
dependencies:
- base >=4.9 && <5.0
- persistent ==2.9.2
- persistent-template ==2.6.0
- persistent-postgresql
- dotenv
- wai-extra
- wai-cors
- mtl
- hslogger
- fast-logger
- http-types
- random
- time
- optparse-applicative
- utf8-string
- base64-bytestring
- hedis
library:
  source-dirs: src
  ghc-options: -fwarn-unused-imports
  exposed-modules:
  - API
  - API.Service
  - Cli
  - Config
  - Db
  - Elasticsearch
  - Logger
  - Models
  - Model.BlogPost
  - Model.Image
  - Model.User
  - Utils
  dependencies:
  - base >=4.9 && <5.0
  - aeson
  - bloodhound
  - bytestring
  - http-client
  - http-types
  - monad-control
  - monad-logger
  - servant
  - servant-auth
  - servant-multipart
  - servant-server
  - transformers
  - wai
  - warp
  - text
  - containers
  - fast-logger
  - unordered-containers
  - safe
  - parser-combinators
  - filepath
  - directory
  - uuid
  - bcrypt
  - imagemagick
executables:
  donnabot-service:
    main: app/Main.hs
    ghc-options: -fwarn-unused-imports
    dependencies:
    - donnabot-service
    - wai
    - warp
    - monad-logger
    - safe
    - text
    - bytestring
  es:
    main: app/ES.hs
    ghc-options: -fwarn-unused-imports
    dependencies:
    - donnabot-service
    - text
    - bloodhound

