name: landscape-service
version: '0.2.0.0'
synopsis: landscape service
description: inalandscape.dev API Service
category: Web
author: Donna <donna@kott.is>
maintainer: Donna <donna@kott.is>
copyright: 2021 Donna
license: MIT
git: https://www.gitlab.com/naglalakk/landscape-service
dependencies:
- base >=4.13 && <5.0
- persistent
- persistent-template
- persistent-postgresql
- dotenv
- wai-extra
- wai-cors
- mtl
- http-types
- random
- time
- optparse-applicative
- utf8-string
- base64-bytestring
- hedis
- co-log
- monad-logger
- typerep-map
library:
  source-dirs: src
  ghc-options: 
  - -fwarn-unused-imports
  - -fwrite-ide-info
  - -hiedir=./hie
  exposed-modules:
  - Api
  - Api.BlogPost
  - Api.Exhibition
  - Api.Item
  - Api.Media
  - Api.Token
  - Api.User
  - Api.Service
  - Cli
  - Config
  - Db
  - Elasticsearch
  - Logger
  - Models
  - Model.BlogPost
  - Model.Exhibition
  - Model.Image
  - Model.Item
  - Model.User
  - Model.Tag
  - Model.Token
  - Utils
  dependencies:
  - aeson
  - bloodhound
  - bytestring
  - http-client
  - http-types
  - monad-control
  - servant
  - servant-auth
  - servant-multipart ==0.11.6
  - servant-server
  - transformers
  - wai
  - warp
  - text
  - containers
  - unordered-containers
  - safe
  - parser-combinators
  - filepath
  - directory
  - uuid
  - bcrypt
  - imagemagick
executables:
  landscape-cli:
    main: app/Main.hs
    ghc-options: 
    - -fwarn-unused-imports
    - -fwrite-ide-info
    - -hiedir=./hie
    dependencies:
    - landscape-service
    - wai
    - warp
    - monad-logger
    - safe
    - text
    - bytestring
  es:
    main: app/ES.hs
    ghc-options: -fwarn-unused-imports
    dependencies:
    - landscape-service
    - text
    - bloodhound

