name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
    - name: Setup ElasticSearch
      uses: getong/elasticsearch-action@v1
      with:
        # Version of elasticsearch to use
        elasticsearch version: # optional, default is latest
        # The port of host
        host port: # optional, default is 9200
        # The port of container
        container port: # optional, default is 9200
        # the discovery.type envionment
    - name: Install dependencies
      run: |
        cabal update
        cabal install --only-dependencies --enable-tests
    - name: Build
      run: |
        cabal configure --enable-tests
        cabal build
    - name: Run tests
      run: cabal test
